### ISSUE TITLE
Error: Cannot find module './src/stream'

### ISSUE THREAD

**Issue by jpfree** [Pexeus/LTE-Car#1]
pi@raspberrypi:~/onboard $ node index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './src/stream'
Require stack:
- /home/pi/onboard/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pi/onboard/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/onboard/index.js' ]
}
pi@raspberrypi:~/onboard $

**Comment by Pexeus** [comment]
Added

**Comment by pinige** [comment]
pi@raspberrypi:~/LTE-Car/onboard $ node index.js
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'pigpio'
Require stack:
- /home/pi/LTE-Car/onboard/src/control.js
- /home/pi/LTE-Car/onboard/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/pi/LTE-Car/onboard/src/control.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/LTE-Car/onboard/src/control.js',
    '/home/pi/LTE-Car/onboard/index.js'
  ]
}
pi@raspberrypi:~/LTE-Car/onboard $
