### ISSUE TITLE
Cannot find module 'pigpio'

### ISSUE THREAD

**Issue by pinige** [Pexeus/LTE-Car#3]
pi@raspberrypi:~/LTE-Car/onboard $ node index.js
internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module 'pigpio'
Require stack:
- /home/pi/LTE-Car/onboard/src/control.js
- /home/pi/LTE-Car/onboard/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/pi/LTE-Car/onboard/src/control.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/LTE-Car/onboard/src/control.js',
    '/home/pi/LTE-Car/onboard/index.js'
  ]
}
pi@raspberrypi:~/LTE-Car/onboard $

**Comment by Pexeus** [comment]
Npm i pigpio

**Comment by pinige** [comment]
Many thanks for your quick response. I am now getting the following error:

pi@raspberrypi:~/LTE-Car/onboard $ sudo node index.js
Initiating stream
Initiating controls
Initiating telemetry
[Streamer Error]: 2023/05/11 21:50:33 socat[1357] E exactly 2 addresses required (there are 4); use option "-h" for help

[Streamer] Process ended: 1
internal/validators.js:216
    throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received [udp port].
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Socket.send (dgram.js:629:12)
    at dispatch (/home/pi/LTE-Car/onboard/src/ucon.js:155:16)
    at Timeout._onTimeout (/home/pi/LTE-Car/onboard/src/ucon.js:164:13)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  code: 'ERR_SOCKET_BAD_PORT'
}
pi@raspberrypi:~/LTE-Car/onboard $

Any help would be very much appreciated - thank you.

**Comment by Pexeus** [comment]
Check the data/config.json file

**Comment by pinige** [comment]
Okay – I will look into it !
Thank you so much for your help – this project of yours is awesome !

Kind regards
Nigel
